"""empty message

Revision ID: f90a2882c78b
Revises: 
Create Date: 2025-03-07 14:08:42.213483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f90a2882c78b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_ticker',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=13, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('date', 'ticker')
    )
    op.create_index(op.f('ix_daily_ticker_date'), 'daily_ticker', ['date'], unique=False)
    op.create_index(op.f('ix_daily_ticker_ticker'), 'daily_ticker', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_ticker_ticker'), table_name='daily_ticker')
    op.drop_index(op.f('ix_daily_ticker_date'), table_name='daily_ticker')
    op.drop_table('daily_ticker')
    # ### end Alembic commands ###
